# Generated by Django 5.2.6 on 2025-10-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_api', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EducationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_api', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocalityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarkingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('minimum_limit', models.IntegerField()),
                ('count_final_exams', models.IntegerField()),
                ('gpa_limit', models.FloatField()),
                ('updated_at', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RatingGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=50)),
                ('updated_at', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_api', models.IntegerField(unique=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_api', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_api', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('semester_count', models.IntegerField()),
                ('education_period', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.department')),
                ('education_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.educationform')),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.educationtype')),
                ('education_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.educationyear')),
                ('marking_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.markingsystem')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_api', models.IntegerField(unique=True)),
                ('meta_id', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100)),
                ('third_name', models.CharField(blank=True, max_length=100)),
                ('employee_id_number', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.BigIntegerField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('image_full', models.URLField(blank=True, max_length=500)),
                ('year_of_enter', models.IntegerField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=255)),
                ('contract_number', models.CharField(blank=True, max_length=50)),
                ('decree_number', models.CharField(blank=True, max_length=50)),
                ('contract_date', models.BigIntegerField(blank=True, null=True)),
                ('decree_date', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('academic_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.academicdegree')),
                ('academic_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.academicrank')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.department')),
                ('employee_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.employeestatus')),
                ('employee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.employeetype')),
                ('employment_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.employmentform')),
                ('employment_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.employmentstaff')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.gender')),
                ('staff_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.staffposition')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='locality_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.localitytype'),
        ),
        migrations.AddField(
            model_name='department',
            name='structure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.structuretype'),
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_api', models.IntegerField(unique=True)),
                ('total_acload', models.IntegerField(blank=True, null=True)),
                ('resource_count', models.IntegerField()),
                ('in_group', models.CharField(blank=True, max_length=100, null=True)),
                ('at_semester', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('credit', models.IntegerField()),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('curriculum', models.ForeignKey(db_column='_curriculum', on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.curriculum')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.department')),
                ('exam_finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.examfinish')),
                ('rating_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.ratinggrade')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.subject')),
                ('subject_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.subjectblock')),
                ('subject_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.subjecttype')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_load', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hemis_integratsiya.curriculumsubject')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.trainingtype')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_ball', models.IntegerField()),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.examtype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='hemis_integratsiya.curriculumsubject')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumSubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_api', models.IntegerField(unique=True)),
                ('students_count', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('curriculum', models.ForeignKey(db_column='_curriculum', on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.curriculum')),
                ('department', models.ForeignKey(db_column='_department', on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.department')),
                ('education_year', models.ForeignKey(db_column='_education_year', on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.educationyear')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.employee')),
                ('group', models.ForeignKey(db_column='_group', on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.group')),
                ('semester', models.ForeignKey(db_column='_semester', on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.subject')),
                ('curriculum_subject_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.subjectdetail')),
                ('training_type', models.ForeignKey(db_column='_training_type', on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.trainingtype')),
            ],
        ),
    ]
