# Generated by Django 5.2.6 on 2025-10-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemis_integratsiya', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='decree_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='decree_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_form',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_staff',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='staff_position',
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.IntegerField()),
                ('contract_number', models.CharField(blank=True, max_length=50)),
                ('decree_number', models.CharField(blank=True, max_length=50)),
                ('contract_date', models.BigIntegerField(blank=True, null=True)),
                ('decree_date', models.BigIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('hash', models.CharField(blank=True, max_length=128)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hemis_integratsiya.employee')),
                ('employee_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.employeestatus')),
                ('employee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.employeetype')),
                ('employment_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.employmentform')),
                ('employment_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.employmentstaff')),
                ('staff_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.staffposition')),
            ],
            options={
                'verbose_name': 'Xodim tayinlovi',
                'verbose_name_plural': 'Xodim tayinlovlari',
                'unique_together': {('employee', 'meta_id')},
            },
        ),
    ]
