# Generated by Django 5.2.6 on 2025-11-03 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemis_integratsiya', '0002_remove_employee_contract_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_api', models.IntegerField(unique=True)),
                ('student_id_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100)),
                ('third_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.BigIntegerField(blank=True, null=True)),
                ('image_full', models.URLField(blank=True, max_length=500)),
                ('avg_gpa', models.FloatField(default=0.0)),
                ('avg_grade', models.FloatField(default=0.0)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('year_of_enter', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.department')),
                ('education_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.educationform')),
                ('education_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.educationtype')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.gender')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.group')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.specialty')),
                ('student_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis_integratsiya.studentstatus')),
            ],
        ),
    ]
