# Generated by Django 5.2.6 on 2025-11-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hemis_oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Talaba ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Xodim'), ('student', 'Talaba')], default=1, max_length=10, verbose_name='Foydalanuvchi turi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Xodim ID'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id__isnull', False)), fields=('employee_id',), name='unique_employee_id'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('student_id__isnull', False)), fields=('student_id',), name='unique_student_id'),
        ),
    ]
