# Generated by Django 5.2.6 on 2025-10-30 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hemis_integratsiya', '0002_remove_employee_contract_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('textbook', 'Darslik'), ('manual', 'O‘quv/kl. qo‘llanma'), ('mobility', 'Akademik mobilnost'), ('method_guide', 'O‘quv-uslubiy tavsiyanoma'), ('teaching_quality', 'Ta’lim sifati'), ('patent', 'Ixtiroga patent'), ('project', 'Loyihada ishtirok'), ('phd_supervision', 'PhD/DSc rahbarlik'), ('diss_defense', 'Dissertatsiya himoyasi'), ('monograph', 'Monografiya'), ('scopus', 'Scopus maqola'), ('wos', 'Web of Science'), ('oak', 'OAK jurnal'), ('olympiad_mentor', 'Olimpiada/tanlov rahbari'), ('creative_circle', 'Ijodiy/sport to‘garak'), ('media', 'OAVda ishtirok'), ('personal_plan', 'Shaxsiy ish rejasi'), ('discipline', 'Ijro intizomi'), ('phd_topic_approval', 'PhD mavzusini tasdiqlash')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/')),
                ('points_awarded', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Jarayonda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.employeeassignment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.employee')),
            ],
        ),
    ]
