# Generated by Django 5.2.6 on 2025-10-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeactivity',
            name='points_awarded',
        ),
        migrations.AddField(
            model_name='employeeactivity',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Hujjat nomi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='description',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/', verbose_name='Fayl'),
        ),
    ]
