# Generated by Django 5.2.6 on 2025-11-01 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemis_integratsiya', '0002_remove_employee_contract_date_and_more'),
        ('main', '0002_remove_employeeactivity_points_awarded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeactivity',
            options={'verbose_name': 'Xodim faoliyati', 'verbose_name_plural': 'Xodim faoliyatlari'},
        ),
        migrations.AddField(
            model_name='employeeactivity',
            name='final_points',
            field=models.FloatField(default=0.0, verbose_name="Yakuniy ball (o'rtacha)"),
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='activity_type',
            field=models.CharField(choices=[('textbook', 'Darslik'), ('manual', 'O‘quv/kl. qo‘llanma'), ('mobility', 'Akademik mobilnost'), ('method_guide', 'O‘quv-uslubiy tavsiyanoma'), ('teaching_quality', 'Ta’lim sifati'), ('patent', 'Ixtiroga patent'), ('project', 'Xalqaro/Respublika loyihasi'), ('phd_supervision', 'PhD/DSc rahbarlik'), ('diss_defense', 'Dissertatsiya himoyasi'), ('monograph', 'Monografiya'), ('scopus', 'Scopus maqola'), ('wos', 'Web of Science'), ('oak', 'OAK jurnal'), ('olympiad_mentor', 'Olimpiada/tanlov rahbari'), ('creative_circle', 'Ijodiy/sport to‘garak'), ('media', 'OAVda ishtirok'), ('personal_plan', 'Shaxsiy ish rejasi'), ('discipline', 'Ijro intizomi'), ('phd_topic_approval', 'PhD mavzusini tasdiqlash')], max_length=50, verbose_name='Mezon turi'),
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.employeeassignment', verbose_name='Tayinlov'),
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.employee', verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='status',
            field=models.CharField(choices=[('pending', 'Jarayonda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_review_taught', models.BooleanField(default=False, verbose_name="Ta'limni tekshiradi")),
                ('can_review_research', models.BooleanField(default=False, verbose_name='Ilmiy ishlarni tekshiradi')),
                ('can_review_social', models.BooleanField(default=False, verbose_name='Ijtimoiy ishlarni tekshiradi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tekshiruvchi',
                'verbose_name_plural': 'Tekshiruvchilar',
            },
        ),
        migrations.CreateModel(
            name='ActivityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Tasdiqlash'), ('reject', 'Rad etish')], max_length=10, verbose_name='Qaror')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh (rad etishda)')),
                ('points', models.FloatField(default=0.0, verbose_name='Berilgan ball')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.employeeactivity', verbose_name='Faoliyat')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tekshiruvchi')),
            ],
            options={
                'verbose_name': 'Tekshiruv',
                'verbose_name_plural': 'Tekshiruvlar',
                'unique_together': {('activity', 'reviewer')},
            },
        ),
    ]
