# Generated by Django 5.2.6 on 2025-11-01 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employeeactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityreview',
            options={},
        ),
        migrations.AlterField(
            model_name='activityreview',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.employeeactivity'),
        ),
        migrations.AlterField(
            model_name='activityreview',
            name='decision',
            field=models.CharField(choices=[('approve', 'Tasdiqlash'), ('reject', 'Rad etish')], max_length=10),
        ),
    ]
