# Generated by Django 5.2.6 on 2025-11-04 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemis_integratsiya', '0003_studentstatus_student'),
        ('main', '0004_alter_activityreview_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('attendance', 'Dars mashg‘ulotlariga davomati'), ('grades', 'Fanlarni o‘zlashtirishi (a‘lo baholarda)'), ('student_mobility', 'Akademik mobiligi'), ('circle_participation', 'To‘garaklarda ishtirok etishi'), ('student_oak', 'OAK jurnalida maqola'), ('olympiad_award', 'Fan olimpiadasida sovrin'), ('language_cert', 'Chet tili sertifikati'), ('moral_events', 'Ma‘naviy-ma‘rifiy tadbirlarda ishtirok'), ('initiative_award', '“5 tashabbus”, tanlovda ishtirok'), ('social_media', 'Ijtimoiy tarmoqlardagi faollik')], max_length=50)),
                ('section', models.CharField(choices=[('taught', 'Ta’lim faoliyati'), ('research', 'Ilmiy-innovatsion faoliyat'), ('social', 'Ijtimoiy, ma’naviy-ma’rifiy faollik')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Hujjat nomi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='student_evidence/%Y/%m/', verbose_name='Fayl')),
                ('status', models.CharField(choices=[('pending', 'Jarayonda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('final_points', models.FloatField(default=0.0, verbose_name='Yakuniy ball')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis_integratsiya.student')),
            ],
        ),
    ]
