# Generated by Django 5.2.6 on 2025-11-11 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_studentactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='can_review_research',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='can_review_social',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='can_review_taught',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='can_review_employee_research',
            field=models.BooleanField(default=False, verbose_name='Xodimlar: Ilmiy ishlarni tekshiradi'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='can_review_employee_social',
            field=models.BooleanField(default=False, verbose_name='Xodimlar: Ijtimoiy ishlarni tekshiradi'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='can_review_employee_taught',
            field=models.BooleanField(default=False, verbose_name="Xodimlar: Ta'limni tekshiradi"),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='can_review_student_research',
            field=models.BooleanField(default=False, verbose_name='Talabalar: Ilmiy ishlarni tekshiradi'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='can_review_student_social',
            field=models.BooleanField(default=False, verbose_name='Talabalar: Ijtimoiy ishlarni tekshiradi'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='can_review_student_taught',
            field=models.BooleanField(default=False, verbose_name="Talabalar: Ta'limni tekshiradi"),
        ),
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Tasdiqlash'), ('reject', 'Rad etish')], default='approve', max_length=10)),
                ('comment', models.TextField(blank=True, verbose_name='Izoh (rad etishda)')),
                ('points', models.FloatField(default=0.0, verbose_name='Berilgan ball')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.studentactivity')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tekshiruvchi')),
            ],
            options={
                'unique_together': {('activity', 'reviewer')},
            },
        ),
    ]
