"""
Django settings for ShaxsiyReja project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sul+sxz18%hxeqex&&f@^*6#_5v2wcl^k_b_zgi4q7c2w5ese('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
AUTH_USER_MODEL = 'hemis_oauth.CustomUser'
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'hemis_oauth',
    'hemis_integratsiya'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ShaxsiyReja.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ShaxsiyReja.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# settings.py

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Development uchun: barcha static fayllar shu yerda to'planadi
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # 'static' papkasini ulash
]

# Collectstatic ishlatganda fayllar shu yerda to'planadi (production)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# HEMIS OAuth config — .env’dan ham olishingiz mumkin
HEMIS_OAUTH = {
    # "employee"  -> univer.hemis.uz,  "student" -> student.hemis.uz (READMEga qarang)
    # "employee" : "hemis.zarmeduniver.com",
    "student" : "student.zarmeduniver.com",
    "DEFAULT_PROFILE": "student",  # yok"i "student"
    "CLIENT_ID": "7",
    "CLIENT_SECRET": "xSNiEK-_pHJ7irgV_ejyIap-hn43ktB4XNlIXahN",
    "REDIRECT_PATH": "/oauth/hemis/callback/",  # to‘liq URL host bilan birga redirect URIda bo‘ladi
    "SCOPES": "",  # HEMIS’da scope talab qilinmasa, bo‘sh qoldiramiz
    # Kerakli user fields (README bo‘yicha mavjud maydonlar)
      "USER_FIELDS": "id,uuid,type,name,login,picture,email,university_id,phone,firstname,surname,patronymic",
}

# Sayt hosti (redirect URL yasash uchun)
SITE_BASE_URL = "http://127.0.0.1:8000/"  # production domeningiz



LOGIN_URL = 'select'


